# Generated by Django 5.2.12 on 2026-03-16 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_blogpost_contactinquiry_service_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Experience",
        ),
        migrations.DeleteModel(
            name="ProgrammingLanguage",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
